config/routes.rb
Rails.application.routes.draw do
  resources :subject_areas
  resources :uploads
  resources :subjects
  devise_for :users
  resources :unis

  resources :unis do
    resources :subject_areas do
  	   resources :subjects do
            resources :resumes, only: [:index, :new, :create, :destroy]
        end
    end
  end
  get '/university/:id/subjects/new' => 'subjects#new'
  post '/unis/:uni_id/subject_areas/:subject_area_id/subjects/:subject_id/resumes/new' => 'resumes#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "unis#index"
end

app/models/uni.rb
class Uni < ApplicationRecord
	has_many :subject_areas
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/unis_controller.rb
class UnisController < ApplicationController
  before_action :set_uni, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /unis
  # GET /unis.json
  def index
    @unis = Uni.all
  end

  # GET /unis/1
  # GET /unis/1.json
  def show
  end

  # GET /unis/new
  def new
    @uni = Uni.new
  end

  # GET /unis/1/edit
  def edit
  end

  # POST /unis
  # POST /unis.json
  def create
    @uni = Uni.new(uni_params)

    respond_to do |format|
      if @uni.save
        format.html { redirect_to root_path, notice: 'Uni was successfully created.' }
        format.json { render :show, status: :created, location: @uni }
      else
        format.html { render :new }
        format.json { render json: @uni.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unis/1
  # PATCH/PUT /unis/1.json
  def update
    respond_to do |format|
      if @uni.update(uni_params)
        format.html { redirect_to root_path, notice: 'Uni was successfully updated.' }
        format.json { render :show, status: :ok, location: @uni }
      else
        format.html { render :edit }
        format.json { render json: @uni.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unis/1
  # DELETE /unis/1.json
  def destroy
    @uni.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Uni was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uni
      @uni = Uni.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def uni_params
      params.require(:uni).permit(:title, :avatar)
    end
end

app/helpers/unis_helper.rb
module UnisHelper
end

app/views/unis/_form.html.erb
<%= form_for uni, html: {multipart: true} do |f| %>
  <% if uni.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(uni.errors.count, "error") %> prohibited this uni from being saved:</h2>

      <ul>
      <% uni.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/unis/edit.html.erb
<h1>Editing Uni</h1>

<%= render 'form', uni: @uni %>

<%= link_to 'Show', @uni %> |
<%= link_to 'Back', unis_path %>

app/views/unis/index.html.erb
<p id="notice"><%= notice %></p>


<div class="jumbotron">
  <h1 class="display-3">Hallo, Studycat!</h1>
  <p class="lead">Auf dieser Seite findest du alles, was du für dein erfolgreiches Studium brauchst.<br>
  Nach einer einfachen Registrierung stehen dir Mitschriften von anderen Studycats zur Verfügung.</p>
  <hr class="my-2">
  <p>Worauf wartest du also noch? Logge dich ein und werde Teil der Community!</p>
  <p class="lead">
    <%= link_to "Jetzt registrieren!",new_user_registration_path, class: "btn btn-primary btn-lg" %>
  </p>
</div>



<table class="table table-striped">
  
  <tbody>
  <% @unis.each do |uni| %>
      <tr>
      <th scope="row"><%= image_tag uni.avatar.url(:thumb) %></th>
      <td><h2><%= link_to uni.title, uni , class: "Uni" %></h2></td>
      <td><small><%= uni.subject_areas.count %> Fachbereiche</small><br /></td>
      <td><%= link_to 'Show', uni %> | <%= link_to 'Edit', edit_uni_path(uni) %> | <%= link_to 'Destroy', uni, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
   </tbody>
   </table>
<br>

<%= link_to 'Neue Uni hinzufügen', new_uni_path %>

app/views/unis/new.html.erb
<h1>New Uni</h1>

<%= render 'form', uni: @uni %>

<%= link_to 'Back', unis_path %>

app/views/unis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2><%= @uni.title %></h2>
</p>


<table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>#</th>
      <th>Fach</th>
      <th>Beiträge</th>
    </tr>
  </thead>
  <tbody>
  <% for subject_area in @uni.subject_areas %>
    <tr>
      <th><%= subject_area.id %></th>
      <th><%= link_to h(subject_area.title), uni_subject_area_path(@uni,subject_area.id) %></th>
      <th><%= subject_area.subjects.count %></th>
    </tr>
  <% end %>
  </tbody>
  </table>


<%= link_to 'Zurück', unis_path %> |
<%= link_to "Neuer Fachbereich", new_uni_subject_area_path(:uni_id => @uni.id) %>