config/routes.rb
Rails.application.routes.draw do
  resources :subject_areas
  resources :uploads
  resources :subjects
  devise_for :users
  resources :unis

  resources :unis do
    resources :subject_areas do
  	   resources :subjects do
            resources :resumes, only: [:index, :new, :create, :destroy]
        end
    end
  end
  get '/university/:id/subjects/new' => 'subjects#new'
  post '/unis/:uni_id/subject_areas/:subject_area_id/subjects/:subject_id/resumes/new' => 'resumes#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "unis#index"
end

app/models/subject.rb
class Subject < ApplicationRecord
	has_many :resumes
	belongs_to :subject_area
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]
  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject_area = SubjectArea.find(params[:subject][:subject_area_id])
    @subject = @subject_area.subjects.new(subject_params)
    #@subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to uni_subject_area_subject_path(params[:subject][:uni_id],params[:subject][:subject_area_id],@subject.id), notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:title)
    end
    def subject_params_2
     params.require(:subject).permit(:uni_id)
     #Rails.logger.debug("My object: #{hash.inspect}")
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_for(subject) do |f| %>

  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.hidden_field :uni_id, :value => "#{params[:uni_id]}" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.title %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject%>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p>
  <h2><%= @subject.title %></h2>
</p>


<table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>#</th>
      <th>Upload-Name</th>
      <th>Datei</th>
    </tr>
  </thead>
  <tbody>
  <% for resume in @subject.resumes %>
    <tr>
      <th><%= resume.id %></th>
      <th><%= link_to h(resume.name), uni_subject_area_subject_resume_path("#{params[:uni_id]}","#{params[:subject_area_id]}",@subject.id,resume.id) %></th>
      <th><%= link_to "Download Resume", resume.attachment_url,class: "btn btn-primary" %></th>
    </tr>
  <% end %>
  </tbody>
  </table>


<%= link_to 'Zurück', uni_subject_area_path("#{params[:uni_id]}","#{params[:subject_area_id]}") %> |
<%= link_to "Neuer Upload", new_uni_subject_area_subject_resume_path("#{params[:uni_id]}","#{params[:subject_area_id]}",@subject.id) %>