config/routes.rb
Rails.application.routes.draw do
  resources :subject_areas
  resources :uploads
  resources :subjects
  devise_for :users
  resources :unis

  resources :unis do
    resources :subject_areas do
  	   resources :subjects do
            resources :resumes, only: [:index, :new, :create, :destroy]
        end
    end
  end
  get '/university/:id/subjects/new' => 'subjects#new'
  post '/unis/:uni_id/subject_areas/:subject_area_id/subjects/:subject_id/resumes/new' => 'resumes#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "unis#index"
end

app/models/subject_area.rb
class SubjectArea < ApplicationRecord
	belongs_to :uni
	has_many :subjects
end

app/controllers/subject_areas_controller.rb
class SubjectAreasController < ApplicationController
  before_action :set_subject_area, only: [:show, :edit, :update, :destroy]

  # GET /subject_areas
  # GET /subject_areas.json
  def index
    @subject_areas = SubjectArea.all
  end

  # GET /subject_areas/1
  # GET /subject_areas/1.json
  def show
  end

  # GET /subject_areas/new
  def new
    @subject_area = SubjectArea.new
  end

  # GET /subject_areas/1/edit
  def edit
  end

  # POST /subject_areas
  # POST /subject_areas.json
  def create
    @uni = Uni.find(params[:subject_area][:uni_id])
    @subject_area = @uni.subject_areas.new(subject_area_params)
    #@subject_area = SubjectArea.new(subject_area_params)

    respond_to do |format|
      if @subject_area.save
        format.html { redirect_to @subject_area, notice: 'Subject area was successfully created.' }
        format.json { render :show, status: :created, location: @subject_area }
      else
        format.html { render :new }
        format.json { render json: @subject_area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subject_areas/1
  # PATCH/PUT /subject_areas/1.json
  def update
    respond_to do |format|
      if @subject_area.update(subject_area_params)
        format.html { redirect_to @subject_area, notice: 'Subject area was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject_area }
      else
        format.html { render :edit }
        format.json { render json: @subject_area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subject_areas/1
  # DELETE /subject_areas/1.json
  def destroy
    @subject_area.destroy
    respond_to do |format|
      format.html { redirect_to uni_subject_areas_url, notice: 'Subject area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject_area
      @subject_area = SubjectArea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_area_params
      params.require(:subject_area).permit(:title)
    end
end

app/helpers/subject_areas_helper.rb
module SubjectAreasHelper
end

app/views/subject_areas/_form.html.erb
<%= form_for(subject_area) do |f| %>
  <% if subject_area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject_area.errors.count, "error") %> prohibited this subject_area from being saved:</h2>

      <ul>
      <% subject_area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.hidden_field :uni_id, :value => "#{params[:uni_id]}" %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subject_areas/edit.html.erb
<h1>Editing Subject Area</h1>

<%= render 'form', subject_area: @subject_area %>

<%= link_to 'Show', @subject_area %> |
<%= link_to 'Back', subject_areas_path %>

app/views/subject_areas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subject Areas</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subject_areas.each do |subject_area| %>
      <tr>
        <td><%= subject_area.title %></td>
        <td><%= link_to 'Show', subject_area %></td>
        <td><%= link_to 'Edit', edit_subject_area_path(subject_area) %></td>
        <td><%= link_to 'Destroy', subject_area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject Area', new_subject_area_path %>

app/views/subject_areas/new.html.erb
<h1>New Subject Area</h1>

<%= render 'form', subject_area: @subject_area %>

<%= link_to 'Back', subject_areas_path %>

app/views/subject_areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2><%= @subject_area.title %></h2>
</p>


<table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>#</th>
      <th>Fach</th>
      <th>Beiträge</th>
    </tr>
  </thead>
  <tbody>
  <% for subject in @subject_area.subjects %>
    <tr>
      <th><%= subject.id %></th>
      <th><%= link_to h(subject.title), uni_subject_area_subject_path("#{params[:uni_id]}",@subject_area.id,subject.id) %></th>
      <th><%= subject.resumes.count %></th>
    </tr>
  <% end %>
  </tbody>
  </table>


<%= link_to 'Zurück', uni_path %> |
<%= link_to "Neues Fach", new_uni_subject_area_subject_path("#{params[:uni_id]}",:subject_area_id => @subject_area.id) %>